In [4]:
import numpy as np
a=[10,20,30,40]
type(a)

list

In [5]:
x=np.array(a)
print(x)

[10 20 30 40]


In [6]:
type(x)

numpy.ndarray

In [7]:
a=[1,2,3,4]
b=[10,20,30,40]
x=np.array([a,b])
print(x)

[[ 1  2  3  4]
 [10 20 30 40]]


In [9]:
a=[1,2,3,4]
b=[10,20,30,40]
x=np.array([a,b])
print(x)

[[ 1  2  3  4]
 [10 20 30 40]]


In [10]:
x=np.array([1,2,3,4],dtype=np.float32)
print(x)

[1. 2. 3. 4.]


In [11]:
x=np.zeros((2,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
x=np.zeros((4,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [22]:
np.ones(3)

array([1., 1., 1.])

In [23]:
np.ones(5, dtype = np.int32)

array([1, 1, 1, 1, 1], dtype=int32)

In [32]:
x=np.random.rand(2,5)
print(x)

[[0.7356686  0.74648065 0.25926949 0.20634209 0.32211567]
 [0.42194751 0.88787022 0.30846329 0.40610319 0.06811891]]


In [30]:

np.random.randint(1,20,size=(3,3))

array([[ 8, 12,  5],
       [17,  5,  3],
       [18,  3, 19]], dtype=int32)

In [35]:
np.random.randn(2,5)

array([[ 0.12751764, -2.67003622,  0.73995895,  0.20955934, -0.25215687],
       [ 0.36055274,  2.12265456,  0.76642866,  1.02930962, -0.31349497]])

In [39]:
np.random.choice([2,3,4,7,8,10])

np.int64(7)

In [42]:
np.full((3,4),1)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [43]:
np.ones((3,3))*10

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [46]:
x=np.eye(4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [48]:
np.arange(5,11)

array([ 5,  6,  7,  8,  9, 10])

In [49]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [54]:
np.linspace(0,1,2)

array([0., 1.])

In [55]:
a=[10,20,30,40,50]
x=np.array(a)
print(x)

[10 20 30 40 50]


In [56]:
x.ndim

1

In [63]:
b=[1,2,3,4,5]
y=np.array([a,b])
print(y)

[[10 20 30 40 50]
 [ 1  2  3  4  5]]


In [64]:
y.ndim

2

In [65]:
y.shape

(2, 5)

In [66]:
y.size

10

In [67]:
a=np.array([3,6,9,12])
print(a)

[ 3  6  9 12]


In [68]:
np.reshape(a,(2,2))

array([[ 3,  6],
       [ 9, 12]])

In [69]:
a.reshape(2,2)

array([[ 3,  6],
       [ 9, 12]])

In [75]:
x=np.arange(1,16)


In [76]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [77]:
x.size

15

In [78]:
x.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [79]:
x=np.arange(1,16)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [80]:
y=x.reshape(3,5)
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [81]:
z=np.transpose(y)
print(z)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [82]:
y.transpose()

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [3]:
import numpy as np
a= np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [4]:
a[2:6]

array([3, 4, 5, 6])

In [5]:
x=np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
x[1,2]

np.int64(6)

In [7]:
x[1][2]

np.int64(6)

In [8]:
x[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [9]:
a=np.arange(1,6)
b=np.arange(6,11)
print(a)
print(b)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [11]:
x=np.vstack((a,b))
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [13]:
x=np.hstack((a,b))
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [14]:
a=np.arange(1,10).reshape(3,3)
b=np.arange(10,19).reshape(3,3)
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [15]:
np.concatenate((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [18]:
np.concatenate((a,b), axis = 1)

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [26]:
import numpy as np
a=np.arange(10,21,2)
b=np.array([[2],[5]])
print(a)
print(b)

[10 12 14 16 18 20]
[[2]
 [5]]


print(b)

In [29]:
z=a+b
print(z)

[[12 14 16 18 20 22]
 [15 17 19 21 23 25]]


In [19]:
a=np.arange(10,21,2)
a+2

array([12, 14, 16, 18, 20, 22])

In [30]:
a-b

array([[ 8, 10, 12, 14, 16, 18],
       [ 5,  7,  9, 11, 13, 15]])

In [31]:
a*b

array([[ 20,  24,  28,  32,  36,  40],
       [ 50,  60,  70,  80,  90, 100]])

In [32]:
a=np.ones((3,3))
b=np.array([2])
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [33]:
print(b)

[2]


In [34]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
a+b

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [36]:
a-b

array([[-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.]])

In [37]:
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [38]:
print(a+5)

[[6. 5. 5. 5.]
 [5. 6. 5. 5.]
 [5. 5. 6. 5.]
 [5. 5. 5. 6.]]


In [39]:
a-1

array([[ 0., -1., -1., -1.],
       [-1.,  0., -1., -1.],
       [-1., -1.,  0., -1.],
       [-1., -1., -1.,  0.]])

In [40]:
a*2

array([[2., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 2.]])

In [41]:
a/0.5

array([[2., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 2.]])

In [42]:
np.sin(a)

array([[0.84147098, 0.        , 0.        , 0.        ],
       [0.        , 0.84147098, 0.        , 0.        ],
       [0.        , 0.        , 0.84147098, 0.        ],
       [0.        , 0.        , 0.        , 0.84147098]])

In [43]:
np.cos(a)

array([[0.54030231, 1.        , 1.        , 1.        ],
       [1.        , 0.54030231, 1.        , 1.        ],
       [1.        , 1.        , 0.54030231, 1.        ],
       [1.        , 1.        , 1.        , 0.54030231]])

In [44]:
np.sqrt(a)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [46]:
a=np.arange(5,15,2)
print(a)

[ 5  7  9 11 13]


In [47]:
np.mean(a)

np.float64(9.0)

In [48]:
np.median(a)

np.float64(9.0)

In [49]:
np.std(a)

np.float64(2.8284271247461903)

In [50]:
a=np.array([[1,6],[4,3]])
print(a)

[[1 6]
 [4 3]]


In [51]:
print(np.min(a,axis=0))

[1 3]


In [53]:
print(np.max(a, axis = 1))

[6 4]


In [54]:
print(np.max(a,axis=0))

[4 6]


In [55]:
a=np.array([1,4,3,10,20])
x=np.sort(a,kind='mergesort')
print(x)

[ 1  3  4 10 20]


In [56]:
A=np.arange(0,9).reshape(3,3)
B=np.ones((3,3))
print(A)
print(B)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [57]:
np.dot(A,B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])