In [4]:
import numpy as np
a=[10,20,30,40]
type(a)

list

In [5]:
x=np.array(a)
print(x)

[10 20 30 40]


In [6]:
type(x)

numpy.ndarray

In [7]:
a=[1,2,3,4]
b=[10,20,30,40]
x=np.array([a,b])
print(x)

[[ 1  2  3  4]
 [10 20 30 40]]


In [9]:
a=[1,2,3,4]
b=[10,20,30,40]
x=np.array([a,b])
print(x)

[[ 1  2  3  4]
 [10 20 30 40]]


In [10]:
x=np.array([1,2,3,4],dtype=np.float32)
print(x)

[1. 2. 3. 4.]


In [11]:
x=np.zeros((2,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
x=np.zeros((4,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [22]:
np.ones(3)

array([1., 1., 1.])

In [23]:
np.ones(5, dtype = np.int32)

array([1, 1, 1, 1, 1], dtype=int32)

In [32]:
x=np.random.rand(2,5)
print(x)

[[0.7356686  0.74648065 0.25926949 0.20634209 0.32211567]
 [0.42194751 0.88787022 0.30846329 0.40610319 0.06811891]]


In [30]:

np.random.randint(1,20,size=(3,3))

array([[ 8, 12,  5],
       [17,  5,  3],
       [18,  3, 19]], dtype=int32)

In [35]:
np.random.randn(2,5)

array([[ 0.12751764, -2.67003622,  0.73995895,  0.20955934, -0.25215687],
       [ 0.36055274,  2.12265456,  0.76642866,  1.02930962, -0.31349497]])

In [39]:
np.random.choice([2,3,4,7,8,10])

np.int64(7)

In [42]:
np.full((3,4),1)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [43]:
np.ones((3,3))*10

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [46]:
x=np.eye(4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [48]:
np.arange(5,11)

array([ 5,  6,  7,  8,  9, 10])

In [49]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [54]:
np.linspace(0,1,2)

array([0., 1.])

In [55]:
a=[10,20,30,40,50]
x=np.array(a)
print(x)

[10 20 30 40 50]


In [56]:
x.ndim

1

In [63]:
b=[1,2,3,4,5]
y=np.array([a,b])
print(y)

[[10 20 30 40 50]
 [ 1  2  3  4  5]]


In [64]:
y.ndim

2

In [65]:
y.shape

(2, 5)

In [66]:
y.size

10

In [67]:
a=np.array([3,6,9,12])
print(a)

[ 3  6  9 12]


In [68]:
np.reshape(a,(2,2))

array([[ 3,  6],
       [ 9, 12]])

In [69]:
a.reshape(2,2)

array([[ 3,  6],
       [ 9, 12]])

In [75]:
x=np.arange(1,16)


In [76]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [77]:
x.size

15

In [78]:
x.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [79]:
x=np.arange(1,16)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [80]:
y=x.reshape(3,5)
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [81]:
z=np.transpose(y)
print(z)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [82]:
y.transpose()

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])